name: "Assemble"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

jobs:
    flavor:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                flavor: [ Generic, Gplay, Huawei ]
        steps:
            -   uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
            -   name: set up JDK 11
                uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3
                with:
                    distribution: "temurin"
                    java-version: 11
            -   name: Build ${{ matrix.flavor }}
                run: |
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> gradle.properties
                    ./gradlew assemble${{ matrix.flavor }}
